version: '3'
services: 
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
